In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [3]:
a[0, :]

array([0, 1, 2, 3])

In [4]:
a[:, 1]

array([1, 5])

In [6]:
a[1, 1:]



array([5, 6, 7])

In [15]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

#2차원 배열 연습

In [8]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]
             ])

In [9]:
m[1, 2]

7

In [10]:
m[-1, -1]

14

In [11]:
m[1, 1:3]

array([6, 7])

In [12]:
m[1:, 2]

array([ 7, 12])

In [14]:
m[:2, -2:]

array([[3, 4],
       [8, 9]])

Boolean array 인덱싱

In [16]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
    False, True, False, True, False])
a[idx]


array([0, 2, 4, 6, 8])

In [17]:
a % 2
#조건 충족 여부에 따라 0과 1로 출력

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [19]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]
               

array([11, 33, 55, 77, 99])

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [23]:
a[[2, 0, 1], :]
#오호라 이런식으로 순서도 바꿀 수 있음

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

다음 행렬과 같은 배열이 있다.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 10 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 10 남는 수를 찾아라.

In [24]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
x % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [27]:
x % 4 == 1

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False])

In [31]:
x % 3 == 0 and x % 4 ==1 
#와 이거 모르겠다

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
x[x%3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [33]:
x[x%4 == 1]

array([ 1,  5,  9, 13, 17])

In [35]:
x[(x%3 == 0) & (x%4 == 1)]

array([9])

In [36]:
print(x[(x%3 == 0) & (x%4 == 1)])

[9]


In [38]:
xx = np.array([1, 2, 3.0])
xx.dtype #데이터가 손실되지 않는 방향으로 출력

dtype('float64')

각 자료형들  

Inf와 Nan

In [39]:
import numpy as np

a= np.array([1.0, 2.0, -3.0, 0.0])
b = np.array([0.0, 1.0, 0.0, 0.0])
c = a/b

print(c)


[ inf   2. -inf  nan]


/var/folders/34/nfsz0w6s5rl3lqtq7z6j5p_h0000gp/T/ipykernel_26505/18139483.py:5: RuntimeWarning: divide by zero encountered in divide
  c = a/b
/var/folders/34/nfsz0w6s5rl3lqtq7z6j5p_h0000gp/T/ipykernel_26505/18139483.py:5: RuntimeWarning: invalid value encountered in divide
  c = a/b


양수를 0으로 나누면 양의 무한대, 음수를 0으로 나누면 0의 무한대.
0을 0으로 나누면 Nan

*0 배열 연습

In [40]:
a = np.zeros(5)
a.dtype #이걸로 자료형 파악할 수 있다!!

dtype('float64')

In [41]:
a

array([0., 0., 0., 0., 0.])

In [48]:
b = np.zeros((2,3))
b #자료형은 실수형이다

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
c = np.zeros((5, 2), dtype="i")
c #array 명령과 마찬가지로 dtype 인수를 명시하면, 해당 자료형 원소를 가진 배열을 만든다.

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [46]:
type(c)

numpy.ndarray

In [52]:
d = np.zeros(5, dtype="U4")
d
#빈 문자열들 출력

array(['', '', '', '', ''], dtype='<U4')

In [53]:
d[0] = "abc"
d[2] = "ABC"
d[3] = 12
d[4] = "가나다"
d #아예 비어있는 것에 지정을 해주면 새롭게 값이 입력. 
#다만 이미 자료형을 입력했기에, 숫자 입력해도 문자형으로 출력되는 것임

array(['abc', '', 'ABC', '12', '가나다'], dtype='<U4')

*zero가 아닌 ones!!

In [57]:
e = np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

*arange 명령

In [63]:

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(3, 21, 2) #파이썬 for문 range()와 형식 동일함

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

*reshape 명령

In [69]:
a = np.arange(12) 
b = a.reshape(3, 4) #a의 총 배열 개수와 일치해야함. 1이라도 다르면 어긋남
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
#사용하는 원소의 갯수가 정해서 있기 때문에 reshape 명령의
# 형태 튜플의 원소 중 하나는 1이라는 숫자로 대체할 수 있다
#-1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다
a.reshape(3, -1)
#1차원 요소가 몇갠지 모르겠는데, 알아서 열 개수를 나눠주는 것

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a.reshape(5,-1) #이렇게 하면 에러뜸. 12개가 안나눠진다.

ValueError: cannot reshape array of size 12 into shape (5,newaxis)